name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: govee2mqtt

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install cross
        run: cargo install cross

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build cross-platform binaries
        run: |
          ./scripts/build-cross.sh linux/amd64
          ./scripts/build-cross.sh linux/arm64

      - name: Build and push multi-arch Docker image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --push \
            -t ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME:latest \
            -t ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME:${{ github.sha }} .
